
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

------------------
---- MONITORS ----
------------------

-- 1. Load layout generated by nwg-displays if monitors.conf exists
local monitors_conf = os.getenv("HOME") .. "/.config/hypr/monitors.conf"
local f = io.open(monitors_conf, "r")
if f then
  for raw_line in f:lines() do
    local line = raw_line:gsub("#.*", ""):match("^%s*(.-)%s*$")
    if line and line:find("^monitor%s*=") then
      local parts = {}
      for part in line:match("^monitor%s*=%s*(.*)$"):gmatch("[^,]+") do
        table.insert(parts, part:match("^%s*(.-)%s*$"))
      end
      if #parts >= 2 and parts[2] == "disable" then
        hl.monitor({ output = parts[1], disabled = true })
      elseif #parts >= 4 then
        hl.monitor({
          output = parts[1],
          mode = parts[2],
          position = parts[3],
          scale = tonumber(parts[4]) or 1,
        })
      end
    end
  end
  f:close()
end

-- 2. Fallback rule: Any newly plugged / unmatched monitor automatically connects
hl.monitor({
  output = "",
  mode = "preferred",
  position = "auto",
  scale = 1,
})

---------------------------------
---- LAPTOP LID / CLAMSHELL ----
---------------------------------

local internal_display = "eDP-1"

local function is_lid_closed()
  local f = io.open("/proc/acpi/button/lid/LID/state", "r")
  if f then
    local content = f:read("*a")
    f:close()
    return content:find("closed") ~= nil
  end
  return false
end

local function has_external_monitors()
  for _, m in ipairs(hl.get_monitors()) do
    if m.name ~= internal_display then
      return true
    end
  end
  return false
end

local function enable_laptop_screen()
  local monitors_file = os.getenv("HOME") .. "/.config/hypr/monitors.conf"
  local f = io.open(monitors_file, "r")
  local configured = false
  if f then
    for raw_line in f:lines() do
      local line = raw_line:gsub("#.*", ""):match("^%s*(.-)%s*$")
      if line and line:find("^monitor%s*=%s*" .. internal_display) then
        local parts = {}
        for part in line:match("^monitor%s*=%s*(.*)$"):gmatch("[^,]+") do
          table.insert(parts, part:match("^%s*(.-)%s*$"))
        end
        if #parts >= 4 then
          hl.monitor({
            output = internal_display,
            mode = parts[2],
            position = parts[3],
            scale = tonumber(parts[4]) or 1.5,
            disabled = false,
          })
          configured = true
        end
        break
      end
    end
    f:close()
  end
  if not configured then
    hl.monitor({
      output = internal_display,
      mode = "preferred",
      position = "auto",
      scale = 1.5,
      disabled = false,
    })
  end
end

local function disable_laptop_screen()
  hl.monitor({ output = internal_display, disabled = true })
end

local function update_lid_state()
  if is_lid_closed() then
    if has_external_monitors() then
      disable_laptop_screen()
    end
  else
    enable_laptop_screen()
  end
end

-- Apply lid state on configuration load
update_lid_state()

-- Keep monitor state in sync when external displays are plugged or unplugged
hl.on("monitor.added", function()
  if is_lid_closed() and has_external_monitors() then
    disable_laptop_screen()
  end
end)

hl.on("monitor.removed", function()
  if not has_external_monitors() or not is_lid_closed() then
    enable_laptop_screen()
  end
end)

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"
local menu = "wofi --show drun"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function () 
  hl.exec_cmd("waybar")
  hl.exec_cmd("/home/han/.config/hypr/wallpaper.sh")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Qt apps: route theming through qt6ct/qt5ct, which read the Mocha
-- palette in ~/.config/qt{5,6}ct/colors/Mocha.conf. KDE apps (dolphin)
-- take their colours from ~/.config/kdeglobals instead.
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")

-- GTK apps read ~/.config/gtk-3.0 / gtk-4.0 plus the portal's dark preference
hl.env("GTK_THEME", "Adwaita:dark")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 6,
        gaps_out = 12,

        border_size = 2,

        col = {
            -- accent #89b4fa -> mauve #cba6f7, the same accents used by
            -- waybar, wofi, kitty, starship and the sddm greeter
            active_border   = { colors = {"rgba(89b4faff)", "rgba(cba6f7ff)"}, angle = 45 },
            inactive_border = "rgba(31324488)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 8,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = false,
        },

        blur = {
            enabled      = false,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,     -- 0 disables the built-in random wallpapers (hyprpaper draws ours)
        disable_hyprland_logo   = true,  -- our own wallpaper is drawn by hyprpaper
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        repeat_rate  = 40,
        repeat_delay = 250,

        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("systemctl poweroff"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))

-- Print: select a region, copy it to the clipboard and save to
-- ~/Pictures/Screenshots. See ~/.config/hypr/screenshot.sh
hl.bind("Print", hl.dsp.exec_cmd("/home/han/.config/hypr/screenshot.sh"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Workspace → monitor default homes
-- Workspaces are not locked; you can still move them freely.
-- HDMI-A-2 = Xiaomi  → 1 2 3
-- DP-1     = Samsung  → 4 5 6
-- eDP-1    = ThinkPad → 7 8 9  (only active when lid is open)
for _, ws in ipairs({ 1, 2, 3 }) do
    hl.workspace_rule({ workspace = tostring(ws), monitor = "HDMI-A-2", default = (ws == 1) })
end
for _, ws in ipairs({ 4, 5, 6 }) do
    hl.workspace_rule({ workspace = tostring(ws), monitor = "DP-1",     default = (ws == 4) })
end
for _, ws in ipairs({ 7, 8, 9 }) do
    hl.workspace_rule({ workspace = tostring(ws), monitor = "eDP-1",    default = (ws == 7) })
end

-- Super+[1-9,0]: focus workspace on its monitor  |  Super+Shift+[1-9,0]: move window
for i = 1, 10 do
    local key = i % 10 -- key 0 maps to workspace 10
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end
--
-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Laptop lid switch handling (clamshell mode)
hl.bind("switch:on:Lid Switch", function()
  if has_external_monitors() then
    disable_laptop_screen()
  end
end, { locked = true })

hl.bind("switch:off:Lid Switch", function()
  enable_laptop_screen()
end, { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Blur the bar and the launcher (disabled for performance)
-- hl.layer_rule({
--     name         = "blur-waybar",
--     match        = { namespace = "^waybar$" },
--     blur         = true,
--     ignore_alpha = 0.2,
-- })
-- 
-- hl.layer_rule({
--     name         = "blur-wofi",
--     match        = { namespace = "^wofi$" },
--     blur         = true,
--     ignore_alpha = 0.5,
-- })
