-- Generated by nwg-displays on 2026-10-02 at 22:08:23. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.01",
    position = "0x1080",
    scale = 1.5,
    vrr = 0
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@100.0",
    position = "1920x0",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@120.0",
    position = "0x0",
    scale = 1,
    vrr = 0
})
